"""Independent expert-label validation and aggregation.

This module prepares trustworthy expert-reviewed vendor-zone suitability labels
for later supervised ML experiments.

It consumes the files produced by:

    app/expert_review.py

Expected sources
----------------
reports/expert_review/review_queue.csv
reports/expert_review/expert_labels.csv

Outputs
-------
aggregated_expert_labels.csv
    Pair-level review quality, agreement and consensus information.

model_dataset.csv
    Leakage-controlled tabular dataset containing only READY_FOR_MODEL pairs.

expert_label_quality.json
    Audit report covering reviewer coverage, abstentions, disagreement,
    agreement and usable-label counts.

model_feature_manifest.json
    Explicit metadata/feature/target contract for the later training pipeline.

Important
---------
Expert labels are research judgements of suitability based on the evidence
shown to reviewers.

They are NOT:
- permits,
- observed vendor success,
- sales outcomes,
- demand measurements,
- live vacancy verification,
- or labels generated by the MCDA model.

The MCDA score and historical compatibility are deliberately excluded from the
training feature allow-list to reduce circular learning and label leakage.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from itertools import combinations
from pathlib import Path
from typing import Any, Mapping

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]

REVIEW_DIR = (
    ROOT
    / "reports"
    / "expert_review"
)

QUEUE_PATH = (
    REVIEW_DIR
    / "review_queue.csv"
)

LABELS_PATH = (
    REVIEW_DIR
    / "expert_labels.csv"
)

AGGREGATED_PATH = (
    REVIEW_DIR
    / "aggregated_expert_labels.csv"
)

MODEL_DATASET_PATH = (
    REVIEW_DIR
    / "model_dataset.csv"
)

QUALITY_REPORT_PATH = (
    REVIEW_DIR
    / "expert_label_quality.json"
)

FEATURE_MANIFEST_PATH = (
    REVIEW_DIR
    / "model_feature_manifest.json"
)


# ---------------------------------------------------------------------------
# Review contract from app/expert_review.py
# ---------------------------------------------------------------------------

LABEL_FIELDS = (
    "pair_id",
    "vendor_profile_id",
    "business_category",
    "preferred_division",
    "zone_id",
    "reviewer_id",
    "reviewed_at_utc",
    "relevance",
    "recommendation",
    "confidence",
    "reason",
    "evidence_version",
)


QUEUE_REQUIRED_FIELDS = (
    "pair_id",
    "vendor_profile_id",
    "business_category",
    "preferred_division",
    "zone_id",
    "evidence_version",
)


RECOMMENDATION_VALUES = {
    "Sufficient evidence to rate",
    "Insufficient evidence / abstain",
    "Requires site verification",
}


CONFIDENCE_VALUES = {
    "Low",
    "Medium",
    "High",
}


RATING_MIN = 0
RATING_MAX = 4


# ---------------------------------------------------------------------------
# ML feature allow-list
# ---------------------------------------------------------------------------
#
# This is intentionally an ALLOW-LIST rather than a block-list.
#
# If review_queue.csv later gains:
# - MCDA score,
# - ranking,
# - historical compatibility,
# - recommendation output,
# - reviewer information,
# - or other leakage-prone fields,
#
# they will NOT silently enter the supervised model.
#
# These fields correspond to the evidence shown independently to reviewers in
# app/expert_review.py, excluding free-text descriptions/source evidence and
# identity fields.
# ---------------------------------------------------------------------------

CATEGORICAL_FEATURES = (
    "business_category",
    "preferred_division",
    "zone_division",
    "environment_cluster",
    "geometry_status",
    "geometry_method",
)


NUMERIC_FEATURES = (
    "official_capacity",
    "mapped_landuse_coverage_ratio_500m",
    "commercial_poi_count_250m",
    "market_poi_count_500m",
    "food_poi_count_250m",
    "distance_to_major_road_m",
    "distance_to_bus_access_m",
    "bus_count_500m",
    "healthcare_count_500m",
    "education_count_500m",
    "toilet_count_500m",
    "parking_count_500m",
)


MODEL_FEATURE_ALLOWLIST = (
    CATEGORICAL_FEATURES
    + NUMERIC_FEATURES
)


MODEL_METADATA_FIELDS = (
    "pair_id",
    "vendor_profile_id",
    "zone_id",
    "evidence_version",
)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AggregationConfig:
    """Quality-control rules for expert label aggregation."""

    # Minimum independent numeric judgments required for a training label.
    min_raters: int = 3

    # Pair is considered highly disputed when its numeric ratings span more
    # than this many scale points.
    max_rating_range: int = 2

    # Additional dispersion threshold.
    max_rating_std: float = 1.0

    # A single explicit "Requires site verification" judgment blocks that pair
    # from the ML dataset until the evidence/site issue is resolved.
    exclude_if_site_verification_requested: bool = True

    # Reviewer-pair agreement is reported only when the two reviewers share at
    # least this many numeric-rated pairs.
    min_common_pairs_for_kappa: int = 5


@dataclass(frozen=True)
class ReviewerAgreement:
    """Agreement statistics for a pair of reviewers."""

    reviewer_a: str
    reviewer_b: str
    common_rated_pairs: int
    exact_agreement_rate: float
    quadratic_weighted_kappa: float | None


# ---------------------------------------------------------------------------
# Basic helpers
# ---------------------------------------------------------------------------


def _clean_text(
    value: Any,
) -> str:

    if value is None:
        return ""

    return str(
        value
    ).strip()


def _read_csv(
    path: str | Path,
    *,
    required: bool = True,
) -> pd.DataFrame:

    source = Path(
        path
    )

    if not source.exists():

        if required:

            raise FileNotFoundError(
                f"Required review file not found: {source}"
            )

        return pd.DataFrame()


    return pd.read_csv(
        source,
        dtype=str,
    ).fillna("")


def _validate_config(
    config: AggregationConfig,
) -> None:

    if config.min_raters < 1:

        raise ValueError(
            "min_raters must be at least 1"
        )


    if config.max_rating_range < 0:

        raise ValueError(
            "max_rating_range must be nonnegative"
        )


    if (
        not np.isfinite(
            config.max_rating_std
        )

        or config.max_rating_std < 0
    ):

        raise ValueError(
            "max_rating_std must be finite "
            "and nonnegative"
        )


    if (
        config.min_common_pairs_for_kappa
        < 1
    ):

        raise ValueError(
            "min_common_pairs_for_kappa "
            "must be at least 1"
        )


# ---------------------------------------------------------------------------
# Queue validation
# ---------------------------------------------------------------------------


def validate_queue(
    queue: pd.DataFrame,
) -> pd.DataFrame:
    """Validate and normalize the review queue."""

    missing = (
        set(
            QUEUE_REQUIRED_FIELDS
        )
        - set(
            queue.columns
        )
    )


    if missing:

        raise ValueError(
            "Review queue is missing columns: "
            + ", ".join(
                sorted(
                    missing
                )
            )
        )


    result = queue.copy()


    for field in (
        QUEUE_REQUIRED_FIELDS
    ):

        result[
            field
        ] = (
            result[
                field
            ]
            .astype(str)
            .str.strip()
        )


    if (
        result[
            "pair_id"
        ]
        .eq("")
        .any()
    ):

        raise ValueError(
            "Review queue contains empty pair_id"
        )


    if (
        result[
            "pair_id"
        ]
        .duplicated()
        .any()
    ):

        duplicates = sorted(

            result.loc[
                result[
                    "pair_id"
                ].duplicated(
                    keep=False
                ),
                "pair_id",
            ].unique()
        )

        raise ValueError(
            "Review queue contains duplicate "
            f"pair_id values: {duplicates}"
        )


    for field in (
        "vendor_profile_id",
        "business_category",
        "zone_id",
        "evidence_version",
    ):

        if (
            result[
                field
            ]
            .eq("")
            .any()
        ):

            raise ValueError(
                f"Review queue contains empty {field}"
            )


    return result


# ---------------------------------------------------------------------------
# Label validation
# ---------------------------------------------------------------------------


def _parse_relevance(
    value: Any,
) -> int:

    text = _clean_text(
        value
    )


    if not text:

        raise ValueError(
            "relevance is missing"
        )


    try:

        numeric = float(
            text
        )

    except ValueError as exc:

        raise ValueError(
            f"Invalid relevance rating: {value!r}"
        ) from exc


    if (
        not np.isfinite(
            numeric
        )

        or not float(
            numeric
        ).is_integer()
    ):

        raise ValueError(
            "relevance must be an integer "
            "from 0 to 4"
        )


    rating = int(
        numeric
    )


    if not (
        RATING_MIN
        <= rating
        <= RATING_MAX
    ):

        raise ValueError(
            "relevance must be between "
            f"{RATING_MIN} and {RATING_MAX}"
        )


    return rating


def validate_labels(
    labels: pd.DataFrame,
    queue: pd.DataFrame,
) -> pd.DataFrame:
    """Validate labels against the authoritative review queue."""

    missing = (
        set(
            LABEL_FIELDS
        )
        - set(
            labels.columns
        )
    )


    if missing:

        raise ValueError(
            "Expert label file is missing columns: "
            + ", ".join(
                sorted(
                    missing
                )
            )
        )


    result = labels.copy()


    for field in (
        LABEL_FIELDS
    ):

        result[
            field
        ] = (
            result[
                field
            ]
            .astype(str)
            .str.strip()
        )


    if result.empty:

        result[
            "_numeric_relevance"
        ] = pd.Series(
            dtype="Int64"
        )

        return result


    for field in (
        "pair_id",
        "reviewer_id",
        "recommendation",
        "confidence",
        "reason",
        "reviewed_at_utc",
        "evidence_version",
    ):

        if (
            result[
                field
            ]
            .eq("")
            .any()
        ):

            raise ValueError(
                f"Expert labels contain empty {field}"
            )


    # One independent judgment per reviewer per pair.
    duplicate_mask = (
        result.duplicated(
            subset=[
                "pair_id",
                "reviewer_id",
            ],
            keep=False,
        )
    )


    if duplicate_mask.any():

        duplicates = (

            result.loc[
                duplicate_mask,
                [
                    "pair_id",
                    "reviewer_id",
                ],
            ]

            .drop_duplicates()

            .to_dict(
                orient="records"
            )
        )

        raise ValueError(
            "Duplicate reviewer/pair judgments: "
            f"{duplicates}"
        )


    unknown_recommendations = sorted(

        set(
            result[
                "recommendation"
            ]
        )

        - RECOMMENDATION_VALUES
    )


    if unknown_recommendations:

        raise ValueError(
            "Unknown evidence decision values: "
            f"{unknown_recommendations}"
        )


    unknown_confidence = sorted(

        set(
            result[
                "confidence"
            ]
        )

        - CONFIDENCE_VALUES
    )


    if unknown_confidence:

        raise ValueError(
            "Unknown confidence values: "
            f"{unknown_confidence}"
        )


    queue_ids = set(
        queue[
            "pair_id"
        ]
    )


    unknown_pairs = sorted(

        set(
            result[
                "pair_id"
            ]
        )

        - queue_ids
    )


    if unknown_pairs:

        raise ValueError(
            "Labels reference pair IDs not present "
            f"in review queue: {unknown_pairs}"
        )


    # Validate timestamps rather than trusting arbitrary text.
    parsed_times = pd.to_datetime(
        result[
            "reviewed_at_utc"
        ],
        errors="coerce",
        utc=True,
    )


    if parsed_times.isna().any():

        bad = result.loc[
            parsed_times.isna(),
            "reviewed_at_utc",
        ].tolist()

        raise ValueError(
            "Invalid reviewed_at_utc values: "
            f"{bad}"
        )


    numeric_relevance: list[
        int | pd.NA
    ] = []


    for row in (
        result.itertuples(
            index=False
        )
    ):

        if (
            row.recommendation
            == "Sufficient evidence to rate"
        ):

            numeric_relevance.append(
                _parse_relevance(
                    row.relevance
                )
            )


        else:

            if _clean_text(
                row.relevance
            ):

                raise ValueError(
                    "relevance must be blank when "
                    f"recommendation={row.recommendation!r}"
                )


            numeric_relevance.append(
                pd.NA
            )


    result[
        "_numeric_relevance"
    ] = pd.array(
        numeric_relevance,
        dtype="Int64",
    )


    # -----------------------------------------------------------------------
    # Ensure saved review metadata still matches the authoritative queue row.
    # -----------------------------------------------------------------------

    queue_lookup = (
        queue.set_index(
            "pair_id",
            drop=False,
        )
    )


    metadata_fields = (
        "vendor_profile_id",
        "business_category",
        "preferred_division",
        "zone_id",
        "evidence_version",
    )


    mismatches: list[
        dict[
            str,
            str,
        ]
    ] = []


    for row in (
        result.itertuples(
            index=False
        )
    ):

        authoritative = (
            queue_lookup.loc[
                row.pair_id
            ]
        )


        for field in (
            metadata_fields
        ):

            label_value = _clean_text(
                getattr(
                    row,
                    field,
                )
            )

            queue_value = _clean_text(
                authoritative[
                    field
                ]
            )


            if (
                label_value
                != queue_value
            ):

                mismatches.append(
                    {
                        "pair_id":
                            row.pair_id,

                        "reviewer_id":
                            row.reviewer_id,

                        "field":
                            field,

                        "label_value":
                            label_value,

                        "queue_value":
                            queue_value,
                    }
                )


    if mismatches:

        raise ValueError(
            "Expert-label metadata does not match "
            "the review queue. First mismatches: "
            f"{mismatches[:10]}"
        )


    return result


# ---------------------------------------------------------------------------
# Reviewer agreement
# ---------------------------------------------------------------------------


def quadratic_weighted_kappa(
    ratings_a: np.ndarray,
    ratings_b: np.ndarray,
    *,
    min_rating: int = RATING_MIN,
    max_rating: int = RATING_MAX,
) -> float | None:
    """Calculate quadratic-weighted Cohen's kappa.

    Used pairwise between reviewers who rated common vendor-zone pairs.
    """

    a = np.asarray(
        ratings_a,
        dtype=int,
    )

    b = np.asarray(
        ratings_b,
        dtype=int,
    )


    if (
        len(
            a
        )
        != len(
            b
        )
    ):

        raise ValueError(
            "Rating arrays must have equal length"
        )


    if len(
        a
    ) == 0:

        return None


    categories = np.arange(
        min_rating,
        max_rating + 1,
    )


    category_count = len(
        categories
    )


    observed = np.zeros(
        (
            category_count,
            category_count,
        ),
        dtype=float,
    )


    for left, right in zip(
        a,
        b,
    ):

        if not (
            min_rating
            <= left
            <= max_rating
            and min_rating
            <= right
            <= max_rating
        ):

            raise ValueError(
                "Ratings outside permitted scale"
            )


        observed[
            left - min_rating,
            right - min_rating,
        ] += 1.0


    histogram_a = (
        observed.sum(
            axis=1
        )
    )

    histogram_b = (
        observed.sum(
            axis=0
        )
    )


    expected = np.outer(
        histogram_a,
        histogram_b,
    ) / float(
        len(
            a
        )
    )


    denominator_scale = float(
        (
            category_count
            - 1
        )
        ** 2
    )


    weights = np.zeros_like(
        observed
    )


    for i in range(
        category_count
    ):

        for j in range(
            category_count
        ):

            weights[
                i,
                j,
            ] = (
                (
                    i
                    - j
                )
                ** 2
            ) / denominator_scale


    observed_disagreement = float(
        np.sum(
            weights
            * observed
        )
    )


    expected_disagreement = float(
        np.sum(
            weights
            * expected
        )
    )


    if np.isclose(
        expected_disagreement,
        0.0,
    ):

        # If both reviewers are constant and agree on every common item,
        # agreement is perfect. Otherwise kappa is undefined.
        if np.array_equal(
            a,
            b,
        ):

            return 1.0

        return None


    return float(
        1.0
        - (
            observed_disagreement
            / expected_disagreement
        )
    )


def reviewer_agreement(
    labels: pd.DataFrame,
    *,
    min_common_pairs: int = 5,
) -> list[
    ReviewerAgreement
]:
    """Calculate pairwise reviewer agreement on numeric-rated pairs."""

    rated = labels.loc[
        labels[
            "_numeric_relevance"
        ].notna()
    ].copy()


    reviewers = sorted(
        rated[
            "reviewer_id"
        ].unique()
    )


    output: list[
        ReviewerAgreement
    ] = []


    for (
        reviewer_a,
        reviewer_b,

    ) in combinations(
        reviewers,
        2,
    ):

        left = (

            rated.loc[
                rated[
                    "reviewer_id"
                ].eq(
                    reviewer_a
                ),
                [
                    "pair_id",
                    "_numeric_relevance",
                ],
            ]

            .rename(
                columns={
                    "_numeric_relevance":
                        "rating_a"
                }
            )
        )


        right = (

            rated.loc[
                rated[
                    "reviewer_id"
                ].eq(
                    reviewer_b
                ),
                [
                    "pair_id",
                    "_numeric_relevance",
                ],
            ]

            .rename(
                columns={
                    "_numeric_relevance":
                        "rating_b"
                }
            )
        )


        common = left.merge(
            right,
            on="pair_id",
            how="inner",
            validate="one_to_one",
        )


        if (
            len(
                common
            )
            < min_common_pairs
        ):

            continue


        ratings_a = (
            common[
                "rating_a"
            ]
            .astype(int)
            .to_numpy()
        )


        ratings_b = (
            common[
                "rating_b"
            ]
            .astype(int)
            .to_numpy()
        )


        exact = float(
            np.mean(
                ratings_a
                == ratings_b
            )
        )


        kappa = (
            quadratic_weighted_kappa(
                ratings_a,
                ratings_b,
            )
        )


        output.append(
            ReviewerAgreement(

                reviewer_a=(
                    reviewer_a
                ),

                reviewer_b=(
                    reviewer_b
                ),

                common_rated_pairs=(
                    len(
                        common
                    )
                ),

                exact_agreement_rate=(
                    exact
                ),

                quadratic_weighted_kappa=(
                    kappa
                ),
            )
        )


    return output


# ---------------------------------------------------------------------------
# Pair-level aggregation
# ---------------------------------------------------------------------------


def aggregate_pair_labels(
    queue: pd.DataFrame,
    labels: pd.DataFrame,
    *,
    config: AggregationConfig | None = None,
) -> pd.DataFrame:
    """Aggregate independent reviewer judgments at pair level."""

    config = (
        config
        or AggregationConfig()
    )

    _validate_config(
        config
    )


    groups = {
        pair_id:
            group.copy()

        for pair_id, group
        in labels.groupby(
            "pair_id"
        )
    }


    rows: list[
        dict[
            str,
            Any,
        ]
    ] = []


    for queue_row in (
        queue.itertuples(
            index=False
        )
    ):

        pair_id = (
            queue_row.pair_id
        )


        reviews = groups.get(
            pair_id,
            labels.iloc[
                0:0
            ].copy(),
        )


        total_reviews = int(
            len(
                reviews
            )
        )


        rated = reviews.loc[
            reviews[
                "_numeric_relevance"
            ].notna()
        ]


        ratings = (
            rated[
                "_numeric_relevance"
            ]
            .astype(float)
            .to_numpy()
        )


        rated_count = int(
            len(
                ratings
            )
        )


        abstain_count = int(
            reviews[
                "recommendation"
            ]
            .eq(
                "Insufficient evidence / abstain"
            )
            .sum()
        )


        site_verification_count = int(
            reviews[
                "recommendation"
            ]
            .eq(
                "Requires site verification"
            )
            .sum()
        )


        if rated_count:

            rating_mean = float(
                np.mean(
                    ratings
                )
            )

            rating_median = float(
                np.median(
                    ratings
                )
            )

            rating_std = float(
                np.std(
                    ratings,
                    ddof=0,
                )
            )

            rating_min = int(
                np.min(
                    ratings
                )
            )

            rating_max = int(
                np.max(
                    ratings
                )
            )

            rating_range = int(
                rating_max
                - rating_min
            )


        else:

            rating_mean = None
            rating_median = None
            rating_std = None
            rating_min = None
            rating_max = None
            rating_range = None


        high_disagreement = bool(

            rated_count >= 2

            and (

                (
                    rating_range
                    is not None

                    and rating_range
                    > config.max_rating_range
                )

                or

                (
                    rating_std
                    is not None

                    and rating_std
                    > config.max_rating_std
                )
            )
        )


        site_verification_flag = bool(
            site_verification_count
            > 0
        )


        if (
            config.exclude_if_site_verification_requested

            and site_verification_flag
        ):

            status = (
                "SITE_VERIFICATION_REQUIRED"
            )


        elif rated_count == 0:

            status = (
                "NO_NUMERIC_RATING"
            )


        elif (
            rated_count
            < config.min_raters
        ):

            status = (
                "NEEDS_MORE_RATERS"
            )


        elif high_disagreement:

            status = (
                "HIGH_DISAGREEMENT"
            )


        else:

            status = (
                "READY_FOR_MODEL"
            )


        target_relevance = (

            rating_median

            if (
                status
                == "READY_FOR_MODEL"
            )

            else None
        )


        target_normalized = (

            (
                target_relevance
                / float(
                    RATING_MAX
                )
            )

            if (
                target_relevance
                is not None
            )

            else None
        )


        confidence_low = int(
            reviews[
                "confidence"
            ]
            .eq(
                "Low"
            )
            .sum()
        )


        confidence_medium = int(
            reviews[
                "confidence"
            ]
            .eq(
                "Medium"
            )
            .sum()
        )


        confidence_high = int(
            reviews[
                "confidence"
            ]
            .eq(
                "High"
            )
            .sum()
        )


        rows.append(
            {
                "pair_id":
                    pair_id,

                "vendor_profile_id":
                    queue_row.vendor_profile_id,

                "business_category":
                    queue_row.business_category,

                "preferred_division":
                    queue_row.preferred_division,

                "zone_id":
                    queue_row.zone_id,

                "evidence_version":
                    queue_row.evidence_version,

                "review_count":
                    total_reviews,

                "rated_count":
                    rated_count,

                "abstain_count":
                    abstain_count,

                "site_verification_count":
                    site_verification_count,

                "confidence_low_count":
                    confidence_low,

                "confidence_medium_count":
                    confidence_medium,

                "confidence_high_count":
                    confidence_high,

                "rating_mean":
                    rating_mean,

                "rating_median":
                    rating_median,

                "rating_std":
                    rating_std,

                "rating_min":
                    rating_min,

                "rating_max":
                    rating_max,

                "rating_range":
                    rating_range,

                "high_disagreement":
                    high_disagreement,

                "site_verification_flag":
                    site_verification_flag,

                "label_status":
                    status,

                "target_relevance":
                    target_relevance,

                "target_normalized":
                    target_normalized,
            }
        )


    return pd.DataFrame(
        rows
    )


# ---------------------------------------------------------------------------
# Leakage-controlled ML dataset
# ---------------------------------------------------------------------------


def build_model_dataset(
    queue: pd.DataFrame,
    aggregated: pd.DataFrame,
) -> tuple[
    pd.DataFrame,
    dict[
        str,
        Any,
    ],
]:
    """Create the later supervised-learning dataset.

    Only fields explicitly allow-listed above may become model features.

    MCDA scores, MCDA ranks, historical business compatibility, reviewer
    identity, reasons, confidence, review decisions and IDs cannot
    accidentally become features.
    """

    ready = aggregated.loc[
        aggregated[
            "label_status"
        ].eq(
            "READY_FOR_MODEL"
        )
    ].copy()


    available_features = [

        field

        for field
        in MODEL_FEATURE_ALLOWLIST

        if field
        in queue.columns
    ]


    missing_configured_features = [

        field

        for field
        in MODEL_FEATURE_ALLOWLIST

        if field
        not in queue.columns
    ]


    queue_columns = list(
        dict.fromkeys(
            [
                *MODEL_METADATA_FIELDS,
                *available_features,
            ]
        )
    )


    evidence = queue[
        queue_columns
    ].copy()


    label_columns = [
        "pair_id",
        "target_relevance",
        "target_normalized",
        "rating_mean",
        "rating_median",
        "rating_std",
        "rating_range",
        "rated_count",
        "review_count",
        "abstain_count",
        "site_verification_count",
    ]


    dataset = evidence.merge(
        ready[
            label_columns
        ],
        on="pair_id",
        how="inner",
        validate="one_to_one",
    )


    # Numeric evidence is explicitly converted. Invalid textual values become
    # missing and will later be handled by the training preprocessing pipeline.
    for field in (
        NUMERIC_FEATURES
    ):

        if field in dataset.columns:

            dataset[
                field
            ] = pd.to_numeric(
                dataset[
                    field
                ],
                errors="coerce",
            )


    # Empty categorical values remain explicitly missing rather than becoming
    # misleading values such as zero.
    for field in (
        CATEGORICAL_FEATURES
    ):

        if field in dataset.columns:

            dataset[
                field
            ] = (
                dataset[
                    field
                ]
                .astype(str)
                .str.strip()
                .replace(
                    "",
                    pd.NA,
                )
            )


    # Targets are numeric and must always exist for READY rows.
    dataset[
        "target_relevance"
    ] = pd.to_numeric(
        dataset[
            "target_relevance"
        ],
        errors="raise",
    )


    dataset[
        "target_normalized"
    ] = pd.to_numeric(
        dataset[
            "target_normalized"
        ],
        errors="raise",
    )


    manifest = {
        "dataset_purpose":
            (
                "Experimental supervised learning of independent "
                "expert suitability judgments."
            ),

        "target":
            "target_relevance",

        "target_scale": {
            "minimum":
                RATING_MIN,

            "maximum":
                RATING_MAX,

            "meaning":
                (
                    "Median independent expert suitability rating "
                    "on the 0–4 ordinal scale."
                ),
        },

        "normalized_target":
            "target_normalized",

        "metadata_columns": [
            field
            for field
            in MODEL_METADATA_FIELDS
            if field
            in dataset.columns
        ],

        "categorical_features": [
            field
            for field
            in CATEGORICAL_FEATURES
            if field
            in dataset.columns
        ],

        "numeric_features": [
            field
            for field
            in NUMERIC_FEATURES
            if field
            in dataset.columns
        ],

        "feature_columns":
            available_features,

        "missing_configured_features":
            missing_configured_features,

        "audit_only_columns": [
            field
            for field
            in (
                "rating_mean",
                "rating_median",
                "rating_std",
                "rating_range",
                "rated_count",
                "review_count",
                "abstain_count",
                "site_verification_count",
            )
            if field
            in dataset.columns
        ],

        "explicitly_excluded_from_features": [
            "pair_id",
            "vendor_profile_id",
            "zone_id",
            "evidence_version",
            "reviewer_id",
            "reviewed_at_utc",
            "reason",
            "confidence",
            "recommendation",
            "relevance",
            "MCDA score",
            "MCDA ranking",
            "MCDA factor contributions",
            "historical business compatibility",
            "same-business historical count",
        ],

        "leakage_policy":
            (
                "Only feature_columns listed in this manifest may be "
                "supplied to the supervised model. Additional queue "
                "columns must not be automatically included."
            ),
    }


    ordered_columns = [

        *[
            field
            for field
            in MODEL_METADATA_FIELDS
            if field
            in dataset.columns
        ],

        *available_features,

        "target_relevance",
        "target_normalized",

        *[
            field
            for field
            in manifest[
                "audit_only_columns"
            ]
        ],
    ]


    dataset = dataset[
        list(
            dict.fromkeys(
                ordered_columns
            )
        )
    ]


    return (
        dataset,
        manifest,
    )


# ---------------------------------------------------------------------------
# Quality report
# ---------------------------------------------------------------------------


def build_quality_report(
    queue: pd.DataFrame,
    labels: pd.DataFrame,
    aggregated: pd.DataFrame,
    dataset: pd.DataFrame,
    manifest: Mapping[
        str,
        Any,
    ],
    *,
    config: AggregationConfig,
) -> dict[
    str,
    Any,
]:
    """Build an auditable label-quality report."""

    agreements = (
        reviewer_agreement(
            labels,
            min_common_pairs=(
                config
                .min_common_pairs_for_kappa
            ),
        )
    )


    valid_kappas = [
        item
        for item
        in agreements
        if (
            item.quadratic_weighted_kappa
            is not None
        )
    ]


    if valid_kappas:

        total_overlap = sum(
            item.common_rated_pairs
            for item
            in valid_kappas
        )


        weighted_kappa = float(

            sum(
                item.quadratic_weighted_kappa
                * item.common_rated_pairs
                for item
                in valid_kappas
            )

            / total_overlap
        )


        weighted_exact = float(

            sum(
                item.exact_agreement_rate
                * item.common_rated_pairs
                for item
                in valid_kappas
            )

            / total_overlap
        )


    else:

        weighted_kappa = None
        weighted_exact = None


    reviewer_rows: list[
        dict[
            str,
            Any,
        ]
    ] = []


    for reviewer_id in sorted(
        labels[
            "reviewer_id"
        ].unique()
    ):

        subset = labels.loc[
            labels[
                "reviewer_id"
            ].eq(
                reviewer_id
            )
        ]


        reviewer_rows.append(
            {
                "reviewer_id":
                    reviewer_id,

                "judgment_count":
                    int(
                        len(
                            subset
                        )
                    ),

                "numeric_rating_count":
                    int(
                        subset[
                            "_numeric_relevance"
                        ]
                        .notna()
                        .sum()
                    ),

                "abstain_count":
                    int(
                        subset[
                            "recommendation"
                        ]
                        .eq(
                            "Insufficient evidence / abstain"
                        )
                        .sum()
                    ),

                "site_verification_count":
                    int(
                        subset[
                            "recommendation"
                        ]
                        .eq(
                            "Requires site verification"
                        )
                        .sum()
                    ),
            }
        )


    status_counts = {
        str(
            key
        ):
            int(
                value
            )
        for key, value
        in aggregated[
            "label_status"
        ]
        .value_counts()
        .to_dict()
        .items()
    }


    rating_distribution = {

        str(
            rating
        ):
            int(
                (
                    labels[
                        "_numeric_relevance"
                    ]
                    == rating
                )
                .sum()
            )

        for rating
        in range(
            RATING_MIN,
            RATING_MAX + 1,
        )
    }


    recommendation_distribution = {
        str(
            key
        ):
            int(
                value
            )
        for key, value
        in labels[
            "recommendation"
        ]
        .value_counts()
        .to_dict()
        .items()
    }


    return {
        "generated_at_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),

        "evaluation_type":
            "INDEPENDENT_EXPERT_LABEL_QUALITY",

        "queue_pair_count":
            int(
                len(
                    queue
                )
            ),

        "label_row_count":
            int(
                len(
                    labels
                )
            ),

        "reviewer_count":
            int(
                labels[
                    "reviewer_id"
                ].nunique()
            ),

        "ready_for_model_count":
            int(
                aggregated[
                    "label_status"
                ]
                .eq(
                    "READY_FOR_MODEL"
                )
                .sum()
            ),

        "model_dataset_row_count":
            int(
                len(
                    dataset
                )
            ),

        "quality_rules":
            asdict(
                config
            ),

        "label_status_counts":
            status_counts,

        "recommendation_distribution":
            recommendation_distribution,

        "rating_distribution":
            rating_distribution,

        "reviewer_summary":
            reviewer_rows,

        "reviewer_pair_agreement": [
            asdict(
                item
            )
            for item
            in agreements
        ],

        "agreement_summary": {
            "metric":
                (
                    "Pairwise quadratic-weighted Cohen kappa "
                    "on common numeric-rated pairs"
                ),

            "minimum_common_pairs":
                config.min_common_pairs_for_kappa,

            "eligible_reviewer_pairs":
                len(
                    agreements
                ),

            "weighted_mean_quadratic_kappa":
                weighted_kappa,

            "weighted_mean_exact_agreement":
                weighted_exact,
        },

        "model_features":
            manifest[
                "feature_columns"
            ],

        "missing_configured_features":
            manifest[
                "missing_configured_features"
            ],

        "target":
            manifest[
                "target"
            ],

        "limitations": [
            (
                "Expert suitability ratings are research judgments "
                "rather than observed business outcomes."
            ),
            (
                "Reviewer agreement does not establish predictive "
                "accuracy or municipal legality."
            ),
            (
                "Pairs requesting site verification are excluded from "
                "the model dataset by default."
            ),
            (
                "MCDA outputs and historical compatibility are excluded "
                "from supervised-model features to reduce circularity."
            ),
            (
                "Small expert samples may produce unstable agreement "
                "statistics and limited supervised-model generalization."
            ),
        ],
    }


# ---------------------------------------------------------------------------
# End-to-end preparation
# ---------------------------------------------------------------------------


def prepare_expert_dataset(
    *,
    queue_path: str | Path = (
        QUEUE_PATH
    ),
    labels_path: str | Path = (
        LABELS_PATH
    ),
    config: AggregationConfig | None = None,
) -> dict[
    str,
    Any,
]:
    """Validate, aggregate and build the expert-supervised dataset."""

    config = (
        config
        or AggregationConfig()
    )

    _validate_config(
        config
    )


    queue = validate_queue(
        _read_csv(
            queue_path
        )
    )


    labels = validate_labels(
        _read_csv(
            labels_path
        ),
        queue,
    )


    aggregated = (
        aggregate_pair_labels(
            queue,
            labels,
            config=config,
        )
    )


    (
        dataset,
        manifest,

    ) = build_model_dataset(
        queue,
        aggregated,
    )


    quality = (
        build_quality_report(
            queue,
            labels,
            aggregated,
            dataset,
            manifest,
            config=config,
        )
    )


    return {
        "queue":
            queue,

        "labels":
            labels,

        "aggregated":
            aggregated,

        "model_dataset":
            dataset,

        "manifest":
            manifest,

        "quality_report":
            quality,
    }


# ---------------------------------------------------------------------------
# Atomic output
# ---------------------------------------------------------------------------


def _write_json_atomic(
    path: Path,
    payload: Mapping[
        str,
        Any,
    ],
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary = (
        path.with_suffix(
            path.suffix
            + ".tmp"
        )
    )


    temporary.write_text(
        json.dumps(
            payload,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )


    temporary.replace(
        path
    )


def _write_csv_atomic(
    path: Path,
    frame: pd.DataFrame,
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary = (
        path.with_suffix(
            path.suffix
            + ".tmp"
        )
    )


    frame.to_csv(
        temporary,
        index=False,
        encoding="utf-8-sig",
    )


    temporary.replace(
        path
    )


def save_expert_dataset(
    prepared: Mapping[
        str,
        Any,
    ],
    *,
    aggregated_path: str | Path = (
        AGGREGATED_PATH
    ),
    model_dataset_path: str | Path = (
        MODEL_DATASET_PATH
    ),
    quality_report_path: str | Path = (
        QUALITY_REPORT_PATH
    ),
    feature_manifest_path: str | Path = (
        FEATURE_MANIFEST_PATH
    ),
) -> dict[
    str,
    Path,
]:
    """Save all expert-label artifacts."""

    aggregated_target = Path(
        aggregated_path
    )

    dataset_target = Path(
        model_dataset_path
    )

    quality_target = Path(
        quality_report_path
    )

    manifest_target = Path(
        feature_manifest_path
    )


    aggregated = prepared.get(
        "aggregated"
    )

    dataset = prepared.get(
        "model_dataset"
    )


    if not isinstance(
        aggregated,
        pd.DataFrame,
    ):

        raise ValueError(
            "prepared result is missing "
            "aggregated DataFrame"
        )


    if not isinstance(
        dataset,
        pd.DataFrame,
    ):

        raise ValueError(
            "prepared result is missing "
            "model_dataset DataFrame"
        )


    _write_csv_atomic(
        aggregated_target,
        aggregated,
    )


    _write_csv_atomic(
        dataset_target,
        dataset,
    )


    _write_json_atomic(
        quality_target,
        prepared[
            "quality_report"
        ],
    )


    _write_json_atomic(
        manifest_target,
        prepared[
            "manifest"
        ],
    )


    return {
        "aggregated_labels":
            aggregated_target,

        "model_dataset":
            dataset_target,

        "quality_report":
            quality_target,

        "feature_manifest":
            manifest_target,
    }


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------


def self_test() -> None:
    """Run a small deterministic in-memory validation test."""

    queue = pd.DataFrame(
        [
            {
                "pair_id": "P1",
                "vendor_profile_id": "VP1",
                "business_category": "food",
                "preferred_division": "Nashik West",
                "zone_id": "Z1",
                "evidence_version": "E1",
                "zone_division": "Nashik West",
                "environment_cluster": "1",
                "geometry_status": "REFERENCE_ONLY",
                "geometry_method": "POINT",
                "official_capacity": "10",
                "commercial_poi_count_250m": "5",
                "distance_to_major_road_m": "100",
            },
            {
                "pair_id": "P2",
                "vendor_profile_id": "VP1",
                "business_category": "food",
                "preferred_division": "Nashik West",
                "zone_id": "Z2",
                "evidence_version": "E1",
                "zone_division": "Nashik West",
                "environment_cluster": "2",
                "geometry_status": "REFERENCE_ONLY",
                "geometry_method": "POINT",
                "official_capacity": "5",
                "commercial_poi_count_250m": "2",
                "distance_to_major_road_m": "250",
            },
        ]
    )


    rows: list[
        dict[
            str,
            str,
        ]
    ] = []


    ratings = {
        "P1": [
            3,
            4,
            3,
        ],
        "P2": [
            1,
            1,
            2,
        ],
    }


    for pair_id, values in (
        ratings.items()
    ):

        queue_row = queue.loc[
            queue[
                "pair_id"
            ].eq(
                pair_id
            )
        ].iloc[
            0
        ]


        for index, rating in enumerate(
            values,
            start=1,
        ):

            rows.append(
                {
                    "pair_id":
                        pair_id,

                    "vendor_profile_id":
                        queue_row[
                            "vendor_profile_id"
                        ],

                    "business_category":
                        queue_row[
                            "business_category"
                        ],

                    "preferred_division":
                        queue_row[
                            "preferred_division"
                        ],

                    "zone_id":
                        queue_row[
                            "zone_id"
                        ],

                    "reviewer_id":
                        f"EXPERT_{index:02d}",

                    "reviewed_at_utc":
                        (
                            "2026-09-30T00:00:00+00:00"
                        ),

                    "relevance":
                        str(
                            rating
                        ),

                    "recommendation":
                        (
                            "Sufficient evidence to rate"
                        ),

                    "confidence":
                        "High",

                    "reason":
                        "Synthetic self-test judgment.",

                    "evidence_version":
                        queue_row[
                            "evidence_version"
                        ],
                }
            )


    queue = validate_queue(
        queue
    )


    labels = validate_labels(
        pd.DataFrame(
            rows
        ),
        queue,
    )


    config = AggregationConfig(
        min_raters=3,
        min_common_pairs_for_kappa=2,
    )


    aggregated = (
        aggregate_pair_labels(
            queue,
            labels,
            config=config,
        )
    )


    dataset, manifest = (
        build_model_dataset(
            queue,
            aggregated,
        )
    )


    if len(
        dataset
    ) != 2:

        raise AssertionError(
            "Self-test expected 2 "
            "READY_FOR_MODEL rows"
        )


    if not (
        aggregated[
            "label_status"
        ]
        .eq(
            "READY_FOR_MODEL"
        )
        .all()
    ):

        raise AssertionError(
            "Self-test labels should "
            "all be READY_FOR_MODEL"
        )


    if (
        "pair_id"
        in manifest[
            "feature_columns"
        ]
    ):

        raise AssertionError(
            "Metadata leaked into model features"
        )


    agreements = reviewer_agreement(
        labels,
        min_common_pairs=2,
    )


    if len(
        agreements
    ) != 3:

        raise AssertionError(
            "Self-test expected three "
            "reviewer-pair agreement results"
        )


    print(
        "Expert label aggregation self-test passed."
    )

    print(
        "Ready pairs:",
        len(
            dataset
        ),
    )

    print(
        "Target values:",
        dataset[
            "target_relevance"
        ].tolist(),
    )

    print(
        "Model features:",
        manifest[
            "feature_columns"
        ],
    )


# ---------------------------------------------------------------------------
# Console output
# ---------------------------------------------------------------------------


def print_summary(
    prepared: Mapping[
        str,
        Any,
    ],
) -> None:

    report = prepared[
        "quality_report"
    ]


    print(
        "\nIndependent Expert Label Quality"
    )

    print(
        "=" * 37
    )


    print(
        "Queue pairs:",
        report[
            "queue_pair_count"
        ],
    )


    print(
        "Saved judgments:",
        report[
            "label_row_count"
        ],
    )


    print(
        "Reviewers:",
        report[
            "reviewer_count"
        ],
    )


    print(
        "Ready for model:",
        report[
            "ready_for_model_count"
        ],
    )


    print(
        "\nLabel status:"
    )


    for (
        status,
        count,

    ) in sorted(
        report[
            "label_status_counts"
        ].items()
    ):

        print(
            f"  {status}: {count}"
        )


    agreement = report[
        "agreement_summary"
    ]


    print(
        "\nReviewer agreement:"
    )


    print(
        "  Eligible reviewer pairs:",
        agreement[
            "eligible_reviewer_pairs"
        ],
    )


    kappa = agreement[
        "weighted_mean_quadratic_kappa"
    ]


    print(
        "  Weighted quadratic kappa:",
        (
            f"{kappa:.4f}"
            if kappa is not None
            else "N/A"
        ),
    )


    exact = agreement[
        "weighted_mean_exact_agreement"
    ]


    print(
        "  Exact agreement:",
        (
            f"{100 * exact:.2f}%"
            if exact is not None
            else "N/A"
        ),
    )


    print(
        "\nML dataset rows:",
        report[
            "model_dataset_row_count"
        ],
    )


    print(
        "Target: median independent "
        "expert relevance (0–4)."
    )


    print(
        "MCDA outputs are excluded "
        "from model features."
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Validate and aggregate independent "
            "expert suitability labels."
        )
    )


    subparsers = (
        parser.add_subparsers(
            dest="command",
            required=True,
        )
    )


    subparsers.add_parser(
        "self-test",
        help=(
            "Run deterministic in-memory "
            "validation without project labels."
        ),
    )


    build_parser = (
        subparsers.add_parser(
            "build",
            help=(
                "Build aggregated labels "
                "and ML-ready dataset."
            ),
        )
    )


    build_parser.add_argument(
        "--queue",
        default=str(
            QUEUE_PATH
        ),
    )


    build_parser.add_argument(
        "--labels",
        default=str(
            LABELS_PATH
        ),
    )


    build_parser.add_argument(
        "--min-raters",
        type=int,
        default=3,
    )


    build_parser.add_argument(
        "--max-rating-range",
        type=int,
        default=2,
    )


    build_parser.add_argument(
        "--max-rating-std",
        type=float,
        default=1.0,
    )


    build_parser.add_argument(
        "--min-common-pairs-for-kappa",
        type=int,
        default=5,
    )


    build_parser.add_argument(
        "--allow-site-verification-flags",
        action="store_true",
        help=(
            "Research-only option. Normally pairs "
            "requesting site verification are excluded."
        ),
    )


    build_parser.add_argument(
        "--no-save",
        action="store_true",
    )


    args = (
        parser.parse_args()
    )


    if (
        args.command
        == "self-test"
    ):

        self_test()

        return


    config = AggregationConfig(

        min_raters=(
            args.min_raters
        ),

        max_rating_range=(
            args.max_rating_range
        ),

        max_rating_std=(
            args.max_rating_std
        ),

        exclude_if_site_verification_requested=(
            not args
            .allow_site_verification_flags
        ),

        min_common_pairs_for_kappa=(
            args
            .min_common_pairs_for_kappa
        ),
    )


    prepared = (
        prepare_expert_dataset(

            queue_path=(
                args.queue
            ),

            labels_path=(
                args.labels
            ),

            config=config,
        )
    )


    print_summary(
        prepared
    )


    if not args.no_save:

        paths = (
            save_expert_dataset(
                prepared
            )
        )


        print(
            "\nSaved:"
        )


        for (
            name,
            path,

        ) in paths.items():

            print(
                f"  {name}: {path}"
            )


if __name__ == "__main__":
    main()