import React,{useEffect,useState,useMemo} from "react";
import {MapContainer,TileLayer,CircleMarker,Popup,useMap} from "react-leaflet";
import "leaflet/dist/leaflet.css";
import {MapPin,Search,ArrowRight,Building2,Users,Layers,BarChart3,FileText,Info,Database,ChevronRight,Filter,BookOpen,ExternalLink} from "lucide-react";
const API=(import.meta.env.VITE_API_BASE||"http://127.0.0.1:8000").replace(/\/$/,"");
const pretty=s=>(s||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
async function get(path){const r=await fetch(API+path);if(!r.ok)throw new Error(`Request failed (${r.status})`);return r.json();}
function useData(path){const [data,setData]=useState(null),[error,setError]=useState("");useEffect(()=>{let live=true;get(path).then(d=>live&&setData(d)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[path]);return {data,error};}
function State({error,children}){return error?<div className="hub-error">{error}</div>:children;}
function Stat({label,value,note}){return <div className="hub-stat"><span>{label}</span><strong>{value??"—"}</strong>{note&&<small>{note}</small>}</div>;}
export function OverviewPage({navigate}){
 const {data:d,error}=useData("/api/overview");const {data:review}=useData("/api/review-summary");
 return <div className="hub-page"><div className="hub-intro"><div><span className="hub-kicker">PROJECT OVERVIEW</span><h1>Vendor zoning platform</h1><p>Explore the zone registry, environmental analysis and recommendation workflow.</p></div><button className="hub-primary" onClick={()=>navigate("recommend")}>Find a zone <ArrowRight size={16}/></button></div>
 <State error={error}><div className="hub-stats"><Stat label="Official zone records" value={d?.official_zones}/><Stat label="Vendor records" value={d?.vendor_records?.toLocaleString()}/><Stat label="GIS references" value={d?.reference_ready}/><Stat label="Environmental groups" value={d?.model?"2":"—"}/></div></State>
 <div className="hub-two"><div className="hub-panel"><div className="hub-panel-head"><h2>Platform workflow</h2><span>01—04</span></div><div className="hub-steps">{[{n:"01",title:"Zone registry",desc:"Official designated-zone records and source descriptions.",page:"zones",icon:Layers},{n:"02",title:"Environmental analysis",desc:"GIS features, reference coverage and K-Means profiling.",page:"analysis",icon:BarChart3},{n:"03",title:"Zone recommendation",desc:"Business-specific ranking with transparent factor contributions.",page:"recommend",icon:MapPin},{n:"04",title:"Expert review",desc:"Independent relevance judgments for future model evaluation.",page:"review",icon:FileText}].map(x=><button key={x.n} className="hub-step" onClick={()=>navigate(x.page)}><span className="step-no">{x.n}</span><div><strong>{x.title}</strong><p>{x.desc}</p></div><ChevronRight size={16}/></button>)}</div></div>
 <div className="hub-panel"><div className="hub-panel-head"><h2>Data at a glance</h2><Database size={17}/></div><div className="hub-data-row"><span>Free vending</span><strong>{d?.zone_types?.FREE??"—"}</strong></div><div className="hub-data-row"><span>Restricted</span><strong>{d?.zone_types?.RESTRICTED??"—"}</strong></div><div className="hub-data-row"><span>No vending</span><strong>{d?.zone_types?.NO_VENDING??"—"}</strong></div><div className="hub-data-row"><span>Unique analytical references</span><strong>{d?.reference_groups??"—"}</strong></div><div className="hub-data-row"><span>Expert judgments recorded</span><strong>{review?.judgment_count??"—"}</strong></div><div className="hub-model-note"><strong>Current recommendation method</strong><p>Weighted MCDA with K-Means environmental profiling. Supervised suitability training is a separate evaluation stage.</p></div></div></div></div>;
}
export function ZoneRegistryPage({openZone}){
 const [q,setQ]=useState(""),[division,setDivision]=useState(""),[type,setType]=useState("");
 const {data:d,error}=useData("/api/catalog");const {data:opts}=useData("/api/options");
 const rows=useMemo(()=>(d?.zones||[]).filter(z=>(!q||(z.zone_id+" "+z.official_description).toLowerCase().includes(q.toLowerCase()))&&(!division||z.division===division)&&(!type||z.zone_type===type)),[d,q,division,type]);
 const [selected,setSelected]=useState(null);
 return <div className="hub-page"><div className="hub-intro"><div><span className="hub-kicker">ZONE REGISTRY</span><h1>Designated zones</h1><p>Browse official records, restrictions and listed capacities.</p></div><span className="hub-count">{rows.length} records</span></div>
 <div className="hub-panel"><div className="hub-filter"><label className="hub-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search zone ID or location"/></label><select value={division} onChange={e=>setDivision(e.target.value)}><option value="">All divisions</option>{opts?.divisions?.map(x=><option key={x}>{x}</option>)}<option>Citywide</option></select><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option value="FREE">Free vending</option><option value="RESTRICTED">Restricted</option><option value="NO_VENDING">No vending</option></select></div>
 <State error={error}><div className="hub-table-wrap"><table className="hub-table"><thead><tr><th>Zone ID</th><th>Official description</th><th>Division</th><th>Type</th><th>Listed capacity</th><th/></tr></thead><tbody>{rows.map(z=><tr key={z.zone_id}><td><strong>{z.zone_id}</strong></td><td>{z.official_description}</td><td>{z.division}</td><td><span className={"hub-status "+z.zone_type}>{pretty(z.zone_type)}</span></td><td>{z.capacity??"—"}</td><td><button className="hub-text-button" onClick={()=>setSelected(z)}>Details <ChevronRight size={14}/></button></td></tr>)}</tbody></table></div>{rows.length===0&&<div className="hub-empty">No records match the selected filters.</div>}</State></div>
 {selected&&<div className="hub-modal-backdrop" onClick={()=>setSelected(null)}><div className="hub-modal" onClick={e=>e.stopPropagation()}><div className="hub-panel-head"><span className="hub-kicker">OFFICIAL ZONE RECORD</span><button className="hub-close" onClick={()=>setSelected(null)}>×</button></div><h2>{selected.zone_id}</h2><p className="hub-description">{selected.official_description}</p><div className="hub-data-row"><span>Division</span><strong>{selected.division}</strong></div><div className="hub-data-row"><span>Zone type</span><strong>{pretty(selected.zone_type)}</strong></div><div className="hub-data-row"><span>Listed capacity</span><strong>{selected.capacity??"Not listed"}</strong></div><div className="hub-data-row"><span>Category</span><strong>{selected.category??"—"}</strong></div><p className="hub-fineprint">Listed capacity is not a live vacancy count. This registry preserves the source designation.</p>{selected.zone_type==="FREE"&&<button className="hub-primary" onClick={()=>{setSelected(null);openZone(selected.division);}}>Find zones in this division <ArrowRight size={15}/></button>}</div></div>}</div>;
}
export function AnalysisPage(){
 const {data:d,error}=useData("/api/overview");const [tab,setTab]=useState("features");
 return <div className="hub-page"><div className="hub-intro"><div><span className="hub-kicker">ENVIRONMENTAL ANALYSIS</span><h1>GIS & model insights</h1><p>Understand how surroundings are converted into comparable zone profiles.</p></div><span className="hub-count">K-Means · K=2</span></div>
 <State error={error}><div className="hub-stats"><Stat label="Zone records" value={d?.official_zones}/><Stat label="Usable references" value={d?.reference_ready}/><Stat label="Reference groups" value={d?.reference_groups}/><Stat label="Shared-reference zones" value={d?.shared_reference_zones}/></div></State>
 <div className="hub-two"><div className="hub-panel"><div className="hub-panel-head"><h2>Environmental feature groups</h2><Layers size={17}/></div>{[{title:"Road accessibility",detail:"Major-road distance, road density and pedestrian-road density.",num:"03"},{title:"Commercial surroundings",detail:"Mapped commercial POIs, markets and food-related POIs.",num:"03"},{title:"Transport access",detail:"Bus-access count and distance to mapped bus access.",num:"02"},{title:"Nearby facilities",detail:"Healthcare, education, toilets and parking.",num:"04"}].map(x=><div className="hub-feature-row" key={x.title}><span>{x.num}</span><div><strong>{x.title}</strong><p>{x.detail}</p></div></div>)}</div>
 <div className="hub-panel"><div className="hub-panel-head"><h2>Model pipeline</h2><BarChart3 size={17}/></div><div className="hub-pipeline">{["Validated official records","Fixed-buffer GIS features","Log transformation & scaling","K-Means environmental clustering","Weighted MCDA recommendation"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div><div className="hub-model-note"><strong>Model roles</strong><p>K-Means discovers environmental groups. The current recommendation score is calculated by weighted MCDA; it is not a supervised prediction.</p></div></div></div>
 <div className="hub-panel hub-analysis-panel"><div className="hub-panel-head"><div><h2>Clustering evaluation</h2><p>Baseline results from the completed K-Means experiment.</p></div></div><div className="hub-eval-grid"><div><span>K=2 silhouette</span><strong>0.3159</strong></div><div><span>K=2 stability ARI</span><strong>1.0000</strong></div><div><span>K=4 silhouette</span><strong>0.2993</strong></div><div><span>K=4 stability ARI</span><strong>0.9595</strong></div></div><p className="hub-fineprint">These are unsupervised clustering metrics, not recommendation accuracy. K=4 remains an experimental alternative; K=2 is the current baseline.</p></div></div>;
}
export function ReviewPage(){
 const {data:d,error}=useData("/api/review-summary");
 return <div className="hub-page"><div className="hub-intro"><div><span className="hub-kicker">MODEL EVALUATION</span><h1>Expert review</h1><p>Collect independent judgments to evaluate business–zone suitability.</p></div></div><State error={error}><div className="hub-stats"><Stat label="Review queue" value={d?.queue_count??"—"}/><Stat label="Judgments saved" value={d?.judgment_count??"—"}/><Stat label="Reviewers" value={d?.reviewer_count??"—"}/><Stat label="Rated pairs" value={d?.rated_count??"—"}/></div></State>
 <div className="hub-two"><div className="hub-panel"><div className="hub-panel-head"><h2>Review workflow</h2><FileText size={17}/></div><div className="hub-steps">{[{n:"01",title:"Select a review pair",desc:"Choose a business profile and designated zone."},{n:"02",title:"Inspect source evidence",desc:"Review location descriptions and environmental measurements."},{n:"03",title:"Record independent judgment",desc:"Rate relevance from 0–4, provide confidence and written reasons."},{n:"04",title:"Compare models",desc:"Use held-out judgments to evaluate the baseline and future supervised models."}].map(x=><div className="hub-step static" key={x.n}><span className="step-no">{x.n}</span><div><strong>{x.title}</strong><p>{x.desc}</p></div></div>)}</div></div><div className="hub-panel"><div className="hub-panel-head"><h2>Local reviewer interface</h2><ExternalLink size={17}/></div><p className="hub-description">The expert-review tool runs separately in Streamlit. It hides recommendation scores during judging and stores a reproducible review queue.</p><div className="hub-command">python -m streamlit run app/expert_review.py</div><p className="hub-fineprint">Run the command from your project root, then open the local URL shown in the terminal. Reviewers should use distinct IDs and may abstain when evidence is insufficient.</p><div className="hub-model-note"><strong>Evaluation status</strong><p>Independent labels are collected separately from historical associations. No supervised accuracy is claimed until a suitable held-out evaluation has been completed.</p></div></div></div></div>;
}
